# Generated by Django 3.2.12 on 2022-03-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=10)),
                ('author_name', models.CharField(max_length=10)),
                ('book_price', models.IntegerField()),
                ('book_quantity', models.IntegerField()),
            ],
        ),
    ]
